name: Deploy to Deno

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: exrector-denoproxy-76
          entrypoint: proxy.ts